[tool.poetry]
name = "emoji-demo"
version = "0.1.0"
description = ""
authors = ["James Haggerty <james.haggerty@morsemicro.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
emoji = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
